version: '3.7'

services:
  web_app:
    build: ./web-app
    ports:
      - 3000:3000
    volumes:
      - ./web-app:/usr/node/app
      - /usr/node/app/node_modules/
  db:
    image: postgres:10.6
    restart: always
    environment:
      POSTGRES_DB: swarm
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432